### ISSUE TITLE
配合其他组件一起使用弹出式组件时出现的BUG

### ISSUE THREAD

**Issue by enootttt** [liluanhui/birdpaper-ui#28]
Tooltip、Trigger包括所有使用到Trigger的组件
比如配合Table组件使用的时候，Table组件的滚动条并不会让Trigger的left和top值发生变化

**Comment by liluanhui** [comment]
> Tooltip、Trigger包括所有使用到Trigger的组件 比如配合Table组件使用的时候，Table组件的滚动条并不会让Trigger的left和top值发生变化

收到，我会在下个版本修复此问题，感谢反馈！

**Comment by liluanhui** [comment]
问题已修复，在版本 `2.2.1` 中，`Trigger` 组件新增了 `updateAtScroll` 和 `scrollToClose` 可选属性，用于监听滚动元素，并自动触发 position 更新，以及滚动时自动触发关闭。

`Select` 等涉及到的组件均启用了 `updateAtScroll`
